#!/usr/bin/env bash
#display information about subdomains
subdomains=( "www" "lb-01" "web-01" "web-02" )
domain="$1"
sub="$2"

display () {
	sub="$2"
	INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP=$(echo "$INFO" | awk '{print $5}')
	RECORD=$(echo "$INFO" | awk '{print $4}')
	echo -e "The subdomain $sub is a $RECORD record and points to $IP"
}

if [ $# -eq 1 ]; then
	for subs in "${subdomains[@]}"; do
		display "$domain" "$subs"
	done
elif [ $# -eq 2 ]; then
	display "$domain" "$sub"
fi
