#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i '24i\    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
