#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i '24i\    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '25i\       error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx restart
