#!/usr/bin/env bash
#configures a server to listen on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
