#!/usr/bin/env bash
# This script prints "Best School" 10 times
# Changes the 9th iteration to "Hi"
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 8 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
